### ISSUE TITLE
Image captioning not working

### ISSUE THREAD

**Issue by medatasci** [sovit-123/SAM_Molmo_Whisper#2]
@sovit-123 Very nice work on the Gradio app!

I'm able to get prompts where the output is a new image working fine.  For example:
point to the people

But, I'm getting the following error when the expected output is text.  Any thoughts?

For example:

caption this image
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 2016, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1569, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "/root/verb-workspace/SAM_Molmo_Whisper/./app.py", line 90, in process_image
    coords = get_coords(output, image)
  File "/root/verb-workspace/SAM_Molmo_Whisper/utils/general.py", line 29, in get_coords
    return coordinates
UnboundLocalError: local variable 'coordinates' referenced before assignment

```
Thanks.
M

**Comment by sovit-123** [comment]
Hello @medatasci 
You are very correct. Actually, to point to objects of interest, Molmo needs user prompt in the format "Point to the object". Any other format, just returns a caption. Although, the caption is returned internally, because it does not contain points, the rest of pipeline that deals with the expected point outputs from Molmo throws an error. I would highly recommend going through the [Molmo technical article](https://molmo.allenai.org/paper.pdf) which tells exactly how Molmo returns outputs.

However, you have a valid point. The user should be able to get caption only as well. I will add the feature as soon as possible.

**Comment by medatasci** [comment]
@sovit-123 That would be great!
The only output I've seen in the Molmo output has been of type <point>.
In https://molmo.allenai.org/, there is frequently image and text outputs.

Again, nice work and thanks for sharing.
M

**Comment by sovit-123** [comment]
@medatasci Hi. Just pushed an update. Now, it will return captions only as well, if you ask it to describe an image.

And yes, the above demo you linked contains all the capabilities of Molmo, which are captioning, pointing, and counting.

Hopefully, this is resolved. I am closing the issue for now.

Thanks.

**Comment by medatasci** [comment]
@sovit-123 Thanks for the really fast response.

After updating I'm still getting an error, any thoughts?

```
Describe this image
Traceback (most recent call last):
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.11/site-packages/gradio/queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.11/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.11/site-packages/gradio/blocks.py", line 2016, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.11/site-packages/gradio/blocks.py", line 1569, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.11/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/root/verb-workspace/SAM_Molmo_Whisper/./app.py", line 89, in process_image
    coords = get_coords(output, image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/verb-workspace/SAM_Molmo_Whisper/utils/general.py", line 32, in get_coords
    return coordinates
           ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'coordinates' where it is not associated with a value
```

**Comment by sovit-123** [comment]
Is it after pulling the latest code?

**Comment by medatasci** [comment]
Yes.

commit 39398e732ff14dcb2acc9a02349f2cd744c2c58c (HEAD -> main, origin/main, origin/HEAD)
Author: sovit-123 <sovitrath5@gmail.com>
Date:   Sun Oct 20 06:45:57 2024 +0530

    Added image captioning-only capability

**Comment by sovit-123** [comment]
That's very odd. May I know what was the prompt?

**Comment by sovit-123** [comment]
And can you try a few other image captioning only prompts and let me know?

**Comment by sovit-123** [comment]
I think I found the issue. I am using this logic in `general.py` to return either the coordinates or prompts.

```python
if 'points' in output_string:
        matches = re.findall(r'(x\d+)="([\d.]+)" (y\d+)="([\d.]+)"', output_string)
        coordinates = [(int(float(x_val)/100*w), int(float(y_val)/100*h)) for _, x_val, _, y_val in matches]
    elif 'point' in output_string:
        match = re.search(r'x="([\d.]+)" y="([\d.]+)"', output_string)
        if match:
            coordinates = [(int(float(match.group(1))/100*w), int(float(match.group(2))/100*h))]
    else:
        return output_string
    
    return coordinates
```

I think, when the output string for caption-only output contains either the word "point" or "points", it is failing in those cases.

Right now, I am working on integrating video tracking. So, will be able to correct this issue after merging that branch only. 
I hope these issues will be very sparse till then.

Let me know your thoughts and thanks for your patience.

**Comment by medatasci** [comment]
Thanks for the update.
What is an example prompt that works for you?

BTW: I noticed that the quality of the segmentations decreased in quality yesterday.  Yesterday they were solid without any open patches, now they look textured with lots of individual patches in a grid-like pattern.

**Comment by sovit-123** [comment]
You can prompt like this: 
"Caption this image" or "Describe this image in detail"

Regarding the bad results, it mostly happens when there are multiple points close by but for different objects. I have observed that as well. There are a few ways to mitigate that. However, the testing phase for this application is a bit slow because three models get loaded. Furthermore, Molmo alone in int-4 quantized format occupies 6 GB of VRAM (including forward pass), SAM2.1 around 2 GB, and I am running Whisper on CPU which gives decent speed. Because I have a single 10GB GPU, after making changes, the testing part is a bit slow. I will try to think of something to make the development faster as I start adding more functionalities.

**Comment by Ryan7180** [comment]
> You can prompt like this: "Caption this image" or "Describe this image in detail"
> 
> Regarding the bad results, it mostly happens when there are multiple points close by but for different objects. I have observed that as well. There are a few ways to mitigate that. However, the testing phase for this application is a bit slow because three models get loaded. Furthermore, Molmo alone in int-4 quantized format occupies 6 GB of VRAM (including forward pass), SAM2.1 around 2 GB, and I am running Whisper on CPU which gives decent speed. Because I have a single 10GB GPU, after making changes, the testing part is a bit slow. I will try to think of something to make the development faster as I start adding more functionalities.

Hi, can you tell me the reason why multiple points close for different objects the results are so bad.

**Comment by sovit-123** [comment]
@Ryan7180 
Although it is difficult to answer precisely, I think it mostly depends on the pixel intensities and grouping. When there are multiple points for a single object or similar object, the model works extremely well. However, when the image contains vastly different objects and Molmo points to almost all the objects, it seems that SAM2.1 gets confused as to where one distinct object ends and where another begins. 

I completely realise that the above is a very generalized, high-level answer. I will try to dig deeper.

**Comment by Ryan7180** [comment]
> [@Ryan7180](https://github.com/Ryan7180) Although it is difficult to answer precisely, I think it mostly depends on the pixel intensities and grouping. When there are multiple points for a single object or similar object, the model works extremely well. However, when the image contains vastly different objects and Molmo points to almost all the objects, it seems that SAM2.1 gets confused as to where one distinct object ends and where another begins.
> 
> I completely realise that the above is a very generalized, high-level answer. I will try to dig deeper.

Thanks for your reply, Have you tried some new works based on SAM, such as LangSAM, Does that have the same problem with SAM2.1? Another observation is when I try to point objects (using the position pointed out by Molmo) one by one on the SAM website, the results seem not so bad. So I think if we process these points with SAM one by one not process all points to SAM at once, will the results be better? Finally, the results also include the mask of all objects pointed out by molmo.

**Comment by sovit-123** [comment]
Hi @Ryan7180 I have not tried LangSAM but I am looking at some new SAM and pointing models. 

I understand your concern about the sequential processing instead of one-shot processing that gives better results, actually. In fact, this application supports that in the additional inputs dropdown below the prompt box. That will surely give better results. Here is a screenshot for reference.

![Image](https://github.com/user-attachments/assets/2d55c880-6bd2-4ae9-ac31-a679a43ffb87)
